apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
