CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT locations_name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT locations_latitude_range CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT locations_longitude_range CHECK (longitude >= -180 AND longitude <= 180)
);
