CREATE TABLE forecast_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    forecast_time VARCHAR(64) NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload VARCHAR(10000) NOT NULL,
    CONSTRAINT forecast_snapshots_location_time_unique UNIQUE (location_id, forecast_time)
);

CREATE INDEX forecast_snapshots_location_fetched_idx
    ON forecast_snapshots (location_id, fetched_at DESC);
